create table if not exists public.classroom_homework_submissions (
  id bigint generated by default as identity primary key,
  classroom_item_id text not null,
  student_name text not null check (char_length(student_name) between 1 and 100),
  answers jsonb not null,
  score integer not null check (score >= 0),
  total_questions integer not null check (total_questions > 0),
  submitted_at timestamptz not null default now()
);

alter table public.classroom_homework_submissions enable row level security;

create policy "Anyone can submit classroom homework"
on public.classroom_homework_submissions for insert to anon, authenticated
with check (
  score <= total_questions
  and jsonb_typeof(answers) = 'object'
);

create index if not exists classroom_homework_submissions_item_submitted_idx
on public.classroom_homework_submissions (classroom_item_id, submitted_at desc);
