create table if not exists public.classroom_comments (
  id bigint generated by default as identity primary key,
  classroom_item_id text not null,
  name text not null check (char_length(name) between 1 and 100),
  comment text not null check (char_length(comment) between 1 and 2000),
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.classroom_comments enable row level security;

drop policy if exists "Anyone can submit a classroom comment"
on public.classroom_comments;

create policy "Anyone can submit a classroom comment"
on public.classroom_comments for insert to anon, authenticated
with check (approved = false);

drop policy if exists "Only approved classroom comments are public"
on public.classroom_comments;

create policy "Only approved classroom comments are public"
on public.classroom_comments for select to anon, authenticated
using (approved = true);

create index if not exists classroom_comments_item_approved_created_idx
on public.classroom_comments (classroom_item_id, approved, created_at);
